version: "3"

services:

  online-wallet-fake:
    image: gwinkamp/online-wallet-fake:latest
    environment:
      - DbConnectionString=Server=postgres;Port=5432;Database=online-wallet-fake;User Id=postgres;Password=postgres;
      - StorageApiUrl=http://storage-mock:1151
    ports:
      - 8000:80
    depends_on:
      - postgres

  storage-mock:
    image: storage-mock
    ports:
      - 1151:1151

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
